repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: double-quote-string-fixer
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-added-large-files
        args: ['--maxkb=25000']
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, master]
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-bugbear==22.7.1',
            'pep8-naming==0.13.0'
        ]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.961'
    hooks:
    -   id: mypy
